programs:
  P90X3:
    Classic:
      1: Total Synergistics
      2: Agility X
      3: X3 Yoga
      4: The Challenge
      5: CVX
      6: The Warrior
      7: Rest or Dynamix
      8: Total Synergistics
      9: Agility X
      10: X3 Yoga
      11: The Challenge
      12: CVX
      13: The Warrior
      14: Rest or Dynamix
      15: Total Synergistics
      16: Agility X
      17: X3 Yoga
      18: The Challenge
      19: CVX
      20: The Warrior
      21: Rest or Dynamix
      22: Isometrix
      23: Dynamix
      24: Accelerator
      25: Pilates X
      26: CVX
      27: X3 Yoga
      28: Rest or Dynamix
      29: Eccentric Upper
      30: Triometrics
      31: X3 Yoga
      32: Eccentric Lower
      33: Incinerator
      34: MMX
      35: Rest or Dynamix
      36: Eccentric Upper
      37: Triometrics
      38: X3 Yoga
      39: Eccentric Lower
      40: Incinerator
      41: MMX
      42: Rest or Dynamix
      43: Eccentric Upper
      44: Triometrics
      45: X3 Yoga
      46: Eccentric Lower
      47: Incinerator
      48: MMX
      49: Rest or Dynamix
      50: Isometrix
      51: Dynamix
      52: Accelerator
      53: Pilates X
      54: CVX
      55: X3 Yoga
      56: Rest or Dynamix
      57: Decelerator
      58: Agility X
      59: The Challenge or Complex Upper
      60: X3 Yoga
      61: Triometrics
      62: Total Synergistics or Complex Lower
      63: Rest or Dynamix
      64: Decelerator
      65: MMX
      66: Eccentric Upper
      67: Triometrics
      68: Pilates X
      69: Eccentric Lower
      70: Rest or Dynamix
      71: Decelerator
      72: Agility X
      73: The Challenge or Complex Upper
      74: X3 Yoga
      75: Triometrics
      76: Total Synergistics or Complex Lower
      77: Rest or Dynamix
      78: Decelerator
      79: MMX
      80: Eccentric Upper
      81: Triometrics
      82: Pilates X
      83: Eccentric Lower
      84: Rest or Dynamix
      85: Isometrix
      86: Accelerator
      87: Pilates X
      88: X3 Yoga
      89: Dynamix
      90: Rest or Dynamix
    Mass:
      1: Total Synergistics
      2: Agility X
      3: X3 Yoga
      4: The Challenge
      5: Pilates X
      6: Incinerator
      7: Rest or Dynamix
      8: Total Synergistics
      9: Agility X
      10: X3 Yoga
      11: The Challenge
      12: Pilates X
      13: Incinerator
      14: Rest or Dynamix
      15: Total Synergistics
      16: Agility X
      17: X3 Yoga
      18: The Challenge
      19: Pilates X
      20: Incinerator
      21: Rest or Dynamix
      22: Isometrix
      23: Dynamix
      24: The Warrior
      25: Pilates X
      26: Agility X
      27: X3 Yoga
      28: Rest or Dynamix
      29: Eccentric Upper
      30: Eccentric Lower
      31: X3 Yoga
      32: Eccentric Upper
      33: Eccentric Lower
      34: MMX
      35: Rest or Dynamix
      36: Eccentric Upper
      37: Eccentric Lower
      38: X3 Yoga
      39: Eccentric Upper
      40: Eccentric Lower
      41: MMX
      42: Rest or Dynamix
      43: Eccentric Upper
      44: Eccentric Lower
      45: X3 Yoga
      46: Eccentric Upper
      47: Eccentric Lower
      48: MMX
      49: Rest or Dynamix
      50: Isometrix
      51: Dynamix
      52: The Warrior
      53: Pilates X
      54: Decelerator
      55: X3 Yoga
      56: Rest or Dynamix
      57: Eccentric Upper
      58: Eccentric Lower
      59: X3 Yoga
      60: Eccentric Upper
      61: Eccentric Lower
      62: MMX
      63: Rest or Dynamix
      64: Total Synergistics
      65: Agility X
      66: X3 Yoga
      67: The Challenge
      68: Pilates X
      69: Incinerator
      70: Rest or Dynamix
      71: Eccentric Upper
      72: Eccentric Lower
      73: X3 Yoga
      74: Eccentric Upper
      75: Eccentric Lower
      76: MMX
      77: Rest or Dynamix
      78: Total Synergistics
      79: Agility X
      80: X3 Yoga
      81: The Challenge
      82: Pilates X
      83: Incinerator
      84: Rest or Dynamix
      85: Isometrix
      86: X3 Yoga
      87: Decelerator
      88: Eccentric Lower
      89: Eccentric Upper
      90: Dynamix
  MAX30:
    Classic:
      1: Cardio Challenge
      2: Tabata Power
      3: Sweat Intervals
      4: Tabata Power
      5: Friday Fight: Round 1
      6: Rest or Pulse
      7: Rest
      8: Cardio Challenge
      9: Tabata Power
      10: Sweat Intervals
      11: Tabata Power
      12: Friday Fight: Round 1
      13: Rest or Pulse
      14: Rest
      15: Cardio Challenge
      16: Tabata Power
      17: Sweat Intervals
      18: Tabata Power
      19: Friday Fight: Round 1
      20: Rest or Pulse
      21: Rest
      22: Cardio Challenge
      23: Tabata Power
      24: Sweat Intervals
      25: Tabata Power
      26: Friday Fight: Round 1
      27: Rest or Pulse
      28: Rest
      29: Max Out Cardio
      30: Max Out Power
      31: Max Out Sweat
      32: Max Out Strength
      33: Friday Fight: Round 2
      34: Rest or Pulse
      35: Rest
      36: Max Out Cardio
      37: Max Out Power
      38: Max Out Sweat
      39: Max Out Strength
      40: Friday Fight: Round 2
      41: Rest or Pulse
      42: Rest
      43: Max Out Cardio
      44: Max Out Power
      45: Max Out Sweat
      46: Max Out Strength
      47: Friday Fight: Round 2
      48: Rest or Pulse
      49: Rest
      50: Max Out Cardio
      51: Max Out Power
      52: Max Out Sweat
      53: Max Out Strength
      54: Friday Fight: Round 2
      55: Rest or Pulse
      56: Rest
