programs:
  P90X3:
    Classic:
      1: Total Synergistics
      2: Agility X
      3: X3 Yoga
      4: The Challenge
      5: CVX
      6: The Warrior
      7: Rest or Dynamix
      8: Total Synergistics
      9: Agility X
      10: X3 Yoga
      11: The Challenge
      12: CVX
      13: The Warrior
      14: Rest or Dynamix
      15: Total Synergistics
      16: Agility X
      17: X3 Yoga
      18: The Challenge
      19: CVX
      20: The Warrior
      21: Rest or Dynamix
      22: Isometrix
      23: Dynamix
      24: Accelerator
      25: Pilates X
      26: CVX
      27: X3 Yoga
      28: Rest or Dynamix
      29: Eccentric Upper
      30: Triometrics
      31: X3 Yoga
      32: Eccentric Lower
      33: Incinerator
      34: MMX
      35: Rest or Dynamix
      36: Eccentric Upper
      37: Triometrics
      38: X3 Yoga
      39: Eccentric Lower
      40: Incinerator
      41: MMX
      42: Rest or Dynamix
      43: Eccentric Upper
      44: Triometrics
      45: X3 Yoga
      46: Eccentric Lower
      47: Incinerator
      48: MMX
      49: Rest or Dynamix
      50: Isometrix
      51: Dynamix
      52: Accelerator
      53: Pilates X
      54: CVX
      55: X3 Yoga
      56: Rest or Dynamix
      57: Decelerator
      58: Agility X
      59: The Challenge or Complex Upper
      60: X3 Yoga
      61: Triometrics
      62: Total Synergistics or Complex Lower
      63: Rest or Dynamix
      64: Decelerator
      65: MMX
      66: Eccentric Upper
      67: Triometrics
      68: Pilates X
      69: Eccentric Lower
      70: Rest or Dynamix
      71: Decelerator
      72: Agility X
      73: The Challenge or Complex Upper
      74: X3 Yoga
      75: Triometrics
      76: Total Synergistics or Complex Lower
      77: Rest or Dynamix
      78: Decelerator
      79: MMX
      80: Eccentric Upper
      81: Triometrics
      82: Pilates X
      83: Eccentric Lower
      84: Rest or Dynamix
      85: Isometrix
      86: Accelerator
      87: Pilates X
      88: X3 Yoga
      89: Dynamix
      90: Rest or Dynamix
